import React from 'react';

const EduCanadaDetails = () => {
    return (
        <div className='lg:p-4'>
        <div className='lg:px-72 px-2 text-xl font-medium mt-16 mb-10 text-justify'>
            <p>Obtaining your visa is a crucial step when you are a foreign student aspiring to pursue higher studies in Canada. At Generation Abroad, we have the expertise to meet your needs in acquiring your Canadian visa. In order to prepare your documents in accordance with the visa requirements, we offer the necessary advice and assistance.
            The applicant only needs to submit an application for a Study Permit and a Temporary Resident Visa (TRV) in order to obtain a Canadian visa. An international student seeking to study abroad, in this case, Canada, must acquire a Study Permit which is issued by the Immigration, Refugees, and Citizenship Canada (IRCC). Thus, enabling the visa holder to pursue higher education.</p>
        </div>
        <div>
            <h1 className='text-4xl font-medium text-primary text-start lg:ml-72 ml-2 mt-16 mb-9'>Lorem ipsum <span className='text-secondary'>dolor sit amet consectetur.</span></h1>
            <p className='lg:px-72 text-justify px-2 mt-6 mb-16'>Lorem ipsum dolor sit amet consectetur. Ultrices elementum at quis duis amet. Libero et erat purus nibh neque ultrices sed. Ac quis auctor sit elit id non in morbi. Imperdiet iaculis posuere et sit duis eget sapien imperdiet. Scelerisque aliquet ac mollis leo eget et netus placerat. Nec nunc eu venenatis praesent tristique donec aliquam. Semper elementum sed venenatis sapien nunc pretium tellus in. Gravida sed quis facilisis hac lectus purus aliquet pharetra. Arcu vulputate fusce nunc id quisque. Dolor euismod blandit vulputate praesent tempus suspendisse vestibulum. Malesuada aliquam et non etiam vulputate et amet cursus. Massa nibh vulputate iaculis ut lorem tincidunt pellentesque congue sed. Amet id ultrices magna euismod sem id morbi consectetur. Cras mi sagittis ut consequat nibh dolor bibendum tellus. Massa auctor a facilisis augue metus aliquam tristique. Vivamus dictumst in imperdiet ut. Imperdiet mattis a accumsan amet diam eget. Phasellus in enim tincidunt turpis dui turpis urna. Sodales non integer odio id sapien.</p>
        </div> 
        <div>
        <h1 className='text-4xl font-medium text-primary text-start lg:ml-72 ml-2 mt-16 mb-9'>Lorem ipsum <span className='text-secondary'>dolor sit amet consectetur.</span></h1>
            <p className='lg:px-72 text-justify px-2 mt-6 mb-16'>Lorem ipsum dolor sit amet consectetur. Ultrices elementum at quis duis amet. Libero et erat purus nibh neque ultrices sed. Ac quis auctor sit elit id non in morbi. Imperdiet iaculis posuere et sit duis eget sapien imperdiet. Scelerisque aliquet ac mollis leo eget et netus placerat. Nec nunc eu venenatis praesent tristique donec aliquam. 
            Semper elementum sed venenatis sapien nunc pretium tellus in. Gravida sed quis facilisis hac lectus purus aliquet pharetra. Arcu vulputate fusce nunc id quisque. Dolor euismod blandit vulputate praesent tempus suspendisse vestibulum. Malesuada aliquam et non etiam vulputate et amet cursus.</p>
        </div> 
        <div>
        <h1 className='text-4xl font-medium text-primary text-start lg:ml-72 ml-2 mt-16 mb-9'>Lorem ipsum <span className='text-secondary'>dolor sit amet consectetur.</span></h1>
            <p className='lg:px-72 text-justify px-2 mt-6 mb-16'>Lorem ipsum dolor sit amet consectetur. Ultrices nec dolor erat sed eget ullamcorper. Pellentesque turpis lacus dictum tristique. Vulputate eget amet turpis odio. Amet cum feugiat integer diam eget turpis amet. Viverra lacus leo mi odio nunc viverra eget. Egestas ac ipsum ac habitasse felis a velit morbi sed. A urna gravida amet fames sit tempor. Ut non consectetur pellentesque netus arcu commodo turpis mauris porttitor. Id sapien in ipsum convallis. Est ultricies sodales adipiscing tortor tincidunt dui nibh malesuada blandit. Est quisque diam dolor bibendum duis cum morbi sit. Id id ut libero cras sed quisque integer. Egestas mi rutrum ut sed. Imperdiet ac viverra nec non. Gravida viverra lectus gravida placerat mi mauris turpis aliquam accumsan. Nascetur elementum phasellus ullamcorper cras pulvinar vitae interdum adipiscing nulla. A mauris pellentesque semper venenatis pretium sed tellus donec vulputate. Fermentum nulla est interdum et orci turpis varius a. Morbi sit hac eget sollicitudin neque. Diam nunc nisl iaculis ante ac. Placerat vehicula imperdiet pellentesque suspendisse. Hendrerit feugiat eget viverra magnis dui purus enim maecenas pulvinar. Bibendum integer vitae augue consequat tellus. Mi molestie id fringilla diam nisi ullamcorper ornare. Lacinia massa orci ullamcorper laoreet bibendum risus viverra odio nulla. Et elementum pellentesque sed molestie. Cursus blandit tristique magna lorem aliquam adipiscing quis. Aliquam nulla vel feugiat nulla lorem facilisis eget pharetra. Nunc maecenas morbi semper fames posuere imperdiet purus faucibus. Faucibus risus curabitur ac lacinia morbi elementum ipsum venenatis. Netus ut feugiat fringilla mauris. Eget egestas eget odio quis egestas eget etiam. Vitae semper et varius gravida quam lacus amet eu. Egestas mattis fusce augue mauris pretium. Sed sodales tempor eu posuere curabitur. Ullamcorper varius dis ac nascetur risus tempor habitasse eu senectus. Pellentesque in posuere donec arcu viverra enim. Elit tempus orci cursus feugiat posuere dictum est. Vulputate fringilla sit amet pretium aliquam. Pulvinar vitae sem quis vulputate egestas. Adipiscing </p>
        </div> 
        
    </div>
    );
};

export default EduCanadaDetails;